version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
jobs:
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Dockerhub Login
          command: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      - run:
          name: Deploy
          command: make circleci_deploy_pipeline
  test:
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@localhost/Budgetr_test
    docker:
      - image: circleci/ruby:2.7.0-node-browsers-legacy
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
    executor: ruby/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Bundler
          command: gem install bundler -v 2.1.4
      - restore_cache:
        keys:
          - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - gem-cache-v1-{{ arch }}-{{ .Branch }}
          - gem-cache-v1
      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Prep DB
          command: bundle exec rake db:create && bundle exec rake db:migrate
      - run:
          name: Specs
          command: bundle exec rspec

