version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers-legacy
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mysecretpassword
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Prepare Bundler
          command: gem install bundler -v 2.1.4
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Specs
          command: bundle exec rspec

