version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@localhost/Budgetr_test
    docker:
      - image: circleci/ruby:2.7.0-node-browsers-legacy
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Prepare Bundler
          command: gem install bundler -v 2.1.4
      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Prep DB
          command: bundle exec rake db:create && bundle exec rake db:migrate
      - run:
          name: Specs
          command: bundle exec rspec

