 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/item_groups", type: :request do
  # ItemGroup. As you add validations to ItemGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ItemGroup.create! valid_attributes
      get item_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      item_group = ItemGroup.create! valid_attributes
      get item_group_url(item_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_item_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      item_group = ItemGroup.create! valid_attributes
      get edit_item_group_url(item_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ItemGroup" do
        expect {
          post item_groups_url, params: { item_group: valid_attributes }
        }.to change(ItemGroup, :count).by(1)
      end

      it "redirects to the created item_group" do
        post item_groups_url, params: { item_group: valid_attributes }
        expect(response).to redirect_to(item_group_url(ItemGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ItemGroup" do
        expect {
          post item_groups_url, params: { item_group: invalid_attributes }
        }.to change(ItemGroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post item_groups_url, params: { item_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested item_group" do
        item_group = ItemGroup.create! valid_attributes
        patch item_group_url(item_group), params: { item_group: new_attributes }
        item_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the item_group" do
        item_group = ItemGroup.create! valid_attributes
        patch item_group_url(item_group), params: { item_group: new_attributes }
        item_group.reload
        expect(response).to redirect_to(item_group_url(item_group))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        item_group = ItemGroup.create! valid_attributes
        patch item_group_url(item_group), params: { item_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested item_group" do
      item_group = ItemGroup.create! valid_attributes
      expect {
        delete item_group_url(item_group)
      }.to change(ItemGroup, :count).by(-1)
    end

    it "redirects to the item_groups list" do
      item_group = ItemGroup.create! valid_attributes
      delete item_group_url(item_group)
      expect(response).to redirect_to(item_groups_url)
    end
  end
end
